use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    // Generate icon constants from BMP files
    generate_icon_constants();
}

fn generate_icon_constants() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let icons_dir = manifest_dir.join("assets/icons");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let output_file = out_dir.join("generated_icons.rs");

    // Find all BMP files
    let mut bmp_files = Vec::new();
    if let Ok(entries) = fs::read_dir(&icons_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.extension().and_then(|s| s.to_str()) == Some("bmp") {
                bmp_files.push(path);
            }
        }
    }

    bmp_files.sort();

    // Generate Rust code
    let mut output = String::new();
    output.push_str("// Auto-generated icon constants from BMP files\n");
    output.push_str("//\n");
    output.push_str("// This file is generated by build.rs\n");
    output.push_str("// Do not edit manually!\n\n");

    for bmp_path in &bmp_files {
        let filename = bmp_path.file_stem().unwrap().to_str().unwrap();

        // Remove _icon suffix and convert to SCREAMING_SNAKE_CASE
        let name = if let Some(stripped) = filename.strip_suffix("_icon") {
            stripped
        } else {
            filename
        };
        let const_name = name.to_uppercase();

        // Use absolute path from CARGO_MANIFEST_DIR so include_bytes! can find it
        let abs_path = bmp_path.to_str().unwrap().replace('\\', "/");

        // Generate doc comment
        let doc_name = filename.replace('_', " ");
        output.push_str(&format!("/// {}\n", doc_name));
        output.push_str(&format!(
            "pub const {}: IconData = IconData::from_bmp(include_bytes!(\"{}\"));\n\n",
            const_name, abs_path
        ));
    }

    // Write the generated file
    fs::write(&output_file, output).expect("Failed to write generated icons file");

    // Tell cargo to rerun if any BMP file changes
    for bmp_path in &bmp_files {
        println!("cargo:rerun-if-changed={}", bmp_path.display());
    }

    println!("cargo:rerun-if-changed={}", icons_dir.display());
}
