//! USB CDC-ACM serial task — implements the Deluge USB serial protocol.
//!
//! ## Protocol (version 1.0)
//! Every message on the wire:
//! ```text
//! [len: u16 LE] = 1 + N   (type byte + data bytes; does NOT include itself)
//! [type: u8]
//! [data: N bytes]
//! ```
//! Minimum: 3 bytes (`len=1`, type, no payload).
//!
//! See [`src/controller/usb_serial.h`] for the full message table.

use embassy_futures::select::{Either, select};
use embassy_sync::{blocking_mutex::raw::CriticalSectionRawMutex, channel::Channel};
use embassy_usb::class::cdc_acm::{CdcAcmClass, Receiver, Sender};
use log::{debug, info};

use deluge_bsp::usb::Rusb1Driver;
use deluge_bsp::{cv_gate, pic};

use crate::events::{EVENT_CHANNEL, HardwareEvent};
use crate::tasks::oled as oled_task;

// Firmware version coordinates — must match the version advertised by the
// host-side Deluge library (examples/host-demo/src/deluge.rs).
const MAJOR: u8 = 1;
const MINOR: u8 = 0;
const PATCH: u8 = 0;

// ── Message type constants (matching usb_serial.h) ───────────────────────────

const MSG_FROM_PAD_PRESSED: u8 = 0x01;
const MSG_FROM_PAD_RELEASED: u8 = 0x02;
const MSG_FROM_BUTTON_PRESSED: u8 = 0x03;
const MSG_FROM_BUTTON_RELEASED: u8 = 0x04;
const MSG_FROM_ENCODER_ROTATED: u8 = 0x05;
const MSG_FROM_VERSION: u8 = 0x10;
const MSG_FROM_PONG: u8 = 0x11;
const MSG_FROM_READY: u8 = 0x12;

const MSG_TO_UPDATE_DISPLAY: u8 = 0x20;
const MSG_TO_CLEAR_DISPLAY: u8 = 0x21;
const MSG_TO_SET_PAD_RGB: u8 = 0x22;
const MSG_TO_CLEAR_ALL_PADS: u8 = 0x23;
const MSG_TO_SET_LED: u8 = 0x24;
const MSG_TO_SET_CV: u8 = 0x25;
const MSG_TO_SET_GATE: u8 = 0x26;
const MSG_TO_SET_ALL_PADS: u8 = 0x27;
const MSG_TO_SET_KNOB_INDICATOR: u8 = 0x28;
const MSG_TO_SET_SYNCED_LED: u8 = 0x29;
const MSG_TO_CLEAR_ALL_LEDS: u8 = 0x2A;
const MSG_TO_SET_BRIGHTNESS: u8 = 0x2B;
const MSG_TO_GET_VERSION: u8 = 0x30;
const MSG_TO_PING: u8 = 0x31;

#[inline]
const fn cdc_button_id(raw_button_id: u8) -> u8 {
    144 + raw_button_id
}

/// Protocol replies generated by the OUT (command) handler that must be emitted
/// on the IN endpoint.  They are routed to [`tx_loop`] through [`REPLY_CHANNEL`]
/// so the TX loop remains the *sole* owner of the CDC [`Sender`] — the OUT loop
/// never touches the IN endpoint directly.
#[derive(Clone, Copy)]
enum HostReply {
    Pong,
    Version,
}

/// Replies from the OUT handler awaiting transmission by [`tx_loop`].  Small
/// capacity: only handshake responses (ping/get-version) flow through here.
static REPLY_CHANNEL: Channel<CriticalSectionRawMutex, HostReply, 8> = Channel::new();

// ── Controller pad colour buffer ────────────────────────────────────────────
//
// In controller mode the CDC host sends actual `[r, g, b]` triples for every
// pad.  We keep a local copy so that `MSG_TO_SET_PAD_RGB` (single-pad update)
// can reconstruct the full column-pair that the PIC requires.
//
// Layout: col-major, same as `MSG_TO_SET_ALL_PADS`.
// `offset = (col * 8 + row) * 3`, col ∈ 0..18, row ∈ 0..8.
//
// Written only by `handle_message` (CDC task); read by the same task when
// rebuilding a column-pair.  Safe in a single-threaded cooperative executor.
const CTRL_PADS_LEN: usize = 18 * 8 * 3; // 432 bytes
static mut CONTROLLER_PAD_COLORS: [u8; CTRL_PADS_LEN] = [0u8; CTRL_PADS_LEN];

/// Build a `[[r,g,b]; 16]` column-pair from `CONTROLLER_PAD_COLORS`.
///
/// `pair` 0–8: left column = `pair*2`, right column = `pair*2+1`.
/// `colours[0..8]` = left column rows 0–7; `colours[8..16]` = right column.
///
/// # Safety
/// Must only be called from the CDC task (single writer, cooperative executor).
unsafe fn ctrl_pair_colours(pair: u8) -> [[u8; 3]; 16] {
    let mut colours = [[0u8; 3]; 16];
    let col_l = pair as usize * 2;
    let col_r = col_l + 1;
    // SAFETY: index arithmetic is bounded; CONTROLLER_PAD_COLORS is only
    // accessed from the CDC task in a cooperative executor.
    let base = core::ptr::addr_of!(CONTROLLER_PAD_COLORS) as *const u8;
    for row in 0..8usize {
        let off_l = (col_l * 8 + row) * 3;
        let off_r = (col_r * 8 + row) * 3;
        // SAFETY: `unsafe fn` caller guarantee; inner block required by Rust 2024.
        unsafe {
            colours[row] = [
                base.add(off_l).read(),
                base.add(off_l + 1).read(),
                base.add(off_l + 2).read(),
            ];
            colours[8 + row] = [
                base.add(off_r).read(),
                base.add(off_r + 1).read(),
                base.add(off_r + 2).read(),
            ];
        }
    }
    colours
}

/// Clear `CONTROLLER_PAD_COLORS` and push all-black to the PIC.
async fn clear_controller_pads() {
    // SAFETY: only called from CDC task; no concurrent access.
    unsafe {
        core::ptr::addr_of_mut!(CONTROLLER_PAD_COLORS).write([0u8; CTRL_PADS_LEN]);
    }
    let black = [[0u8; 3]; 16];
    for pair in 0u8..9 {
        pic::set_column_pair_rgb(pair, &black).await;
    }
    pic::done_sending_rows().await;
}

// ── RX accumulation buffer ───────────────────────────────────────────────────

const RX_BUF_SIZE: usize = 2048;

struct RxState {
    buf: [u8; RX_BUF_SIZE],
    pos: usize,
}

impl RxState {
    const fn new() -> Self {
        Self {
            buf: [0; RX_BUF_SIZE],
            pos: 0,
        }
    }

    fn append(&mut self, data: &[u8]) {
        let n = data.len().min(self.buf.len() - self.pos);
        self.buf[self.pos..self.pos + n].copy_from_slice(&data[..n]);
        self.pos += n;
    }

    /// Try to extract one complete message. Returns `Some((type, data_start,
    /// end))` if a full message is buffered; `None` if more data is needed.
    /// Sets `self.pos = 0` if the length field is invalid (resynchronise).
    fn try_frame(&mut self) -> Option<(u8, usize, usize)> {
        if self.pos < 3 {
            return None;
        }
        let len = u16::from_le_bytes([self.buf[0], self.buf[1]]) as usize;
        if len == 0 || len + 2 > self.buf.len() {
            // Bad length — discard and resync.
            self.pos = 0;
            return None;
        }
        let total = 2 + len; // length field (2 bytes) + payload (len bytes)
        if self.pos < total {
            return None;
        }
        Some((self.buf[2], 3, total))
    }

    /// Consume `end` bytes from the front of the buffer (shift remaining).
    fn consume(&mut self, end: usize) {
        let remaining = self.pos.saturating_sub(end);
        self.buf.copy_within(end..self.pos, 0);
        self.pos = remaining;
    }
}

// ── TX helpers ────────────────────────────────────────────────────────────────

/// Encode a CDC-from-Deluge message and write it as one USB packet.
///
/// `type_byte + data` must fit in one 64-byte USB FS bulk packet.
async fn send_msg(
    tx: &mut Sender<'static, Rusb1Driver>,
    type_byte: u8,
    data: &[u8],
) -> Result<(), embassy_usb::driver::EndpointError> {
    let total = 3 + data.len();
    debug_assert!(total <= 64, "CDC TX message too large for one FS packet");
    let mut buf = [0u8; 64];
    let len = 1u16 + data.len() as u16;
    buf[0] = (len & 0xFF) as u8;
    buf[1] = (len >> 8) as u8;
    buf[2] = type_byte;
    buf[3..3 + data.len()].copy_from_slice(data);
    tx.write_packet(&buf[..total]).await
}

// ── Incoming message dispatch ─────────────────────────────────────────────────

async fn handle_message(type_byte: u8, data: &[u8]) {
    match type_byte {
        MSG_TO_UPDATE_DISPLAY => {
            // 768-byte page-major framebuffer (6 pages × 128 columns).
            if data.len() >= deluge_bsp::oled::FRAME_BYTES {
                oled_task::set_cdc_display(&data[..deluge_bsp::oled::FRAME_BYTES]);
            }
        }
        MSG_TO_CLEAR_DISPLAY => {
            oled_task::clear_cdc_display();
        }
        MSG_TO_SET_PAD_RGB => {
            // [col:1][row:1][r:1][g:1][b:1]
            if data.len() >= 5 {
                let col = data[0];
                let row = data[1];
                let r = data[2];
                let g = data[3];
                let b = data[4];
                if col < 18 && row < 8 {
                    // Update the local color buffer and push the affected
                    // column-pair directly to the PIC.
                    let off = (col as usize * 8 + row as usize) * 3;
                    // SAFETY: only written from CDC task; no concurrent access.
                    unsafe {
                        let base = core::ptr::addr_of_mut!(CONTROLLER_PAD_COLORS) as *mut u8;
                        base.add(off).write(r);
                        base.add(off + 1).write(g);
                        base.add(off + 2).write(b);
                    }
                    let pair = col / 2;
                    // SAFETY: called from CDC task only.
                    let colours = unsafe { ctrl_pair_colours(pair) };
                    pic::set_column_pair_rgb(pair, &colours).await;
                    pic::done_sending_rows().await;
                }
            }
        }
        MSG_TO_CLEAR_ALL_PADS => {
            clear_controller_pads().await;
        }
        MSG_TO_SET_LED => {
            // [led_index:1][on:1]
            if data.len() >= 2 {
                let idx = data[0];
                let on = data[1] != 0;
                if on {
                    pic::led_on(idx).await;
                } else {
                    pic::led_off(idx).await;
                }
            }
        }
        MSG_TO_SET_CV => {
            // [channel:1][value_hi:1][value_lo:1]
            if data.len() >= 3 {
                let ch = data[0];
                let value = u16::from_be_bytes([data[1], data[2]]);
                if (ch as usize) < deluge_bsp::cv_gate::NUM_CV_CHANNELS {
                    // Safety: single-threaded; RSPI0_DMA_ACTIVE guard is inside
                    // cv_set_blocking.
                    unsafe {
                        cv_gate::cv_set_blocking(ch, value);
                    }
                }
            }
        }
        MSG_TO_SET_GATE => {
            // [channel:1][on:1]
            if data.len() >= 2 {
                let ch = data[0];
                let on = data[1] != 0;
                if (ch as usize) < deluge_bsp::cv_gate::NUM_GATE_CHANNELS {
                    // Safety: GPIO write only.
                    unsafe {
                        cv_gate::gate_set(ch, on);
                    }
                }
            }
        }
        MSG_TO_SET_ALL_PADS => {
            // [18*8*3 = 432 bytes], col-major: offset = (col*8 + row)*3
            if data.len() >= 18 * 8 * 3 {
                // Copy the full frame into the local buffer, then push
                // all 9 column-pairs to the PIC in one go.
                // SAFETY: only written from CDC task; no concurrent access.
                unsafe {
                    core::ptr::copy_nonoverlapping(
                        data.as_ptr(),
                        core::ptr::addr_of_mut!(CONTROLLER_PAD_COLORS) as *mut u8,
                        CTRL_PADS_LEN,
                    );
                }
                for pair in 0u8..9 {
                    // SAFETY: called from CDC task only.
                    let colours = unsafe { ctrl_pair_colours(pair) };
                    pic::set_column_pair_rgb(pair, &colours).await;
                }
                pic::done_sending_rows().await;
            }
        }
        MSG_TO_SET_KNOB_INDICATOR => {
            // [which:1][b0:1][b1:1][b2:1][b3:1]
            if data.len() >= 5 {
                let which = data[0] & 1;
                let levels = [data[1], data[2], data[3], data[4]];
                pic::set_gold_knob_indicators(which, levels).await;
            }
        }
        MSG_TO_SET_SYNCED_LED => {
            // Controls the GPIO "synced" LED (P6.7).  Note: this pin is also
            // toggled by blink_task; the host can override it by calling this.
            if !data.is_empty() {
                let on = data[0] != 0;
                unsafe {
                    rza1l_hal::gpio::write(6, 7, on);
                }
            }
        }
        MSG_TO_CLEAR_ALL_LEDS => {
            // Turn off all 36 indicator LEDs + gold knob indicators.
            for i in 0..36u8 {
                pic::led_off(i).await;
            }
            pic::set_gold_knob_indicators(0, [0; 4]).await;
            pic::set_gold_knob_indicators(1, [0; 4]).await;
            // Also clear the synced LED.
            unsafe {
                rza1l_hal::gpio::write(6, 7, false);
            }
        }
        MSG_TO_SET_BRIGHTNESS => {
            // [level: 0–25]  0=dimmest, 25=brightest.
            // Maps to PIC SET_REFRESH_TIME: interval = 25 - level.
            if !data.is_empty() {
                let level = data[0].min(25);
                pic::set_refresh_time(25 - level).await;
            }
        }
        MSG_TO_GET_VERSION => {
            // Routed to tx_loop; drop if the reply queue is somehow full.
            let _ = REPLY_CHANNEL.try_send(HostReply::Version);
        }
        MSG_TO_PING => {
            let _ = REPLY_CHANNEL.try_send(HostReply::Pong);
        }
        other => {
            debug!("CDC: unknown message type 0x{:02X}", other);
        }
    }
}

// ── Session loop ─────────────────────────────────────────────────────────────

/// Drive the bidirectional event ↔ command session until the host disconnects.
///
/// IN side of a session.  Sole owner of the CDC [`Sender`].  Serialises hardware
/// events ([`EVENT_CHANNEL`]) and protocol replies ([`REPLY_CHANNEL`]) onto the
/// bulk-IN endpoint.  Returns on the first endpoint error (host disconnect).
///
/// The `select` here is over two **channel receives**, which are cancel-safe:
/// the loser is merely de-registered, never losing a queued item — unlike the
/// old loop's `read_packet`, whose cancellation churned endpoint state.
async fn tx_loop(tx: &mut Sender<'static, Rusb1Driver>) {
    loop {
        let result = match select(REPLY_CHANNEL.receive(), EVENT_CHANNEL.receive()).await {
            Either::First(reply) => match reply {
                HostReply::Pong => send_msg(tx, MSG_FROM_PONG, &[]).await,
                HostReply::Version => send_msg(tx, MSG_FROM_VERSION, &[MAJOR, MINOR, PATCH]).await,
            },
            Either::Second(event) => match event {
                HardwareEvent::PadPressed { col, row } => {
                    send_msg(tx, MSG_FROM_PAD_PRESSED, &[col, row]).await
                }
                HardwareEvent::PadReleased { col, row } => {
                    send_msg(tx, MSG_FROM_PAD_RELEASED, &[col, row]).await
                }
                HardwareEvent::ButtonPressed { id } => {
                    send_msg(tx, MSG_FROM_BUTTON_PRESSED, &[cdc_button_id(id)]).await
                }
                HardwareEvent::ButtonReleased { id } => {
                    send_msg(tx, MSG_FROM_BUTTON_RELEASED, &[cdc_button_id(id)]).await
                }
                HardwareEvent::EncoderRotated { id, delta } => {
                    send_msg(tx, MSG_FROM_ENCODER_ROTATED, &[id, delta as u8]).await
                }
            },
        };
        if result.is_err() {
            return; // endpoint error — host disconnected
        }
    }
}

/// OUT side of a session.  Sole owner of the CDC [`Receiver`].  Reads host
/// command frames and dispatches them; replies that must go back to the host are
/// pushed to [`REPLY_CHANNEL`] for [`tx_loop`].  Returns on the first endpoint
/// error (host disconnect).
async fn rx_loop(rx: &mut Receiver<'static, Rusb1Driver>) {
    let mut rx_state = RxState::new();
    // Must be >= the bulk OUT max packet size (512 at high speed).  embassy-usb's
    // `read_packet` requires a buffer large enough to hold one full packet; a
    // smaller buffer would truncate host frames and drop the FIFO remainder.
    let mut pkt_buf = [0u8; 512];

    loop {
        let n = match rx.read_packet(&mut pkt_buf).await {
            Ok(n) => n,
            Err(_) => return, // endpoint disabled — host disconnected
        };
        rx_state.append(&pkt_buf[..n]);

        // Process all complete frames currently buffered.
        while let Some((type_byte, data_start, end)) = rx_state.try_frame() {
            // Copy out the payload since we borrow rx_state mutably to consume.
            let mut msg_buf = [0u8; RX_BUF_SIZE];
            let data_len = end.saturating_sub(data_start);
            msg_buf[..data_len].copy_from_slice(&rx_state.buf[data_start..end]);
            rx_state.consume(end);
            handle_message(type_byte, &msg_buf[..data_len]).await;
        }
    }
}

// ── Embassy task ─────────────────────────────────────────────────────────────

/// CDC-ACM serial task.
///
/// Loops forever: waits for a host connection (DTR set), sends the READY +
/// VERSION greeting, then drives the bidirectional event ↔ command session
/// until the host disconnects.  On disconnect, clears the host-driven pad
/// matrix and OLED, then falls back to waiting for the next connection.
#[embassy_executor::task]
pub(crate) async fn cdc_task(class: CdcAcmClass<'static, Rusb1Driver>) {
    let (mut tx, mut rx) = class.split();
    loop {
        // Wait for the host to open the port (DTR asserted / endpoint enabled).
        tx.wait_connection().await;
        info!("CDC: host connected");

        // Greet the host with READY + VERSION in a single packet (the host parses
        // both frames out of the one read).
        let greeting = [
            1,
            0,
            MSG_FROM_READY, // READY  : [len=1][type]
            4,
            0,
            MSG_FROM_VERSION,
            MAJOR,
            MINOR,
            PATCH, // VERSION: [len=4][type][maj][min][pat]
        ];
        let r = tx.write_packet(&greeting).await;
        info!("CDC: greeting sent (ok={:?})", r.is_ok());

        // Drive IN and OUT as two independent concurrent loops until the host
        // disconnects.  Unlike the old single `select(receive, read_packet)`
        // loop, neither side cancels the other's endpoint operation during
        // normal traffic — cancellation happens only here, at teardown, when one
        // loop returns on an endpoint error.
        let _ = select(tx_loop(&mut tx), rx_loop(&mut rx)).await;

        // Session ended (host disconnected).  Clear host-set pad colours and the
        // host-supplied OLED framebuffer so the panel goes blank until the next
        // host connects.
        clear_controller_pads().await;
        oled_task::clear_cdc_display();
        info!("CDC: host disconnected");

        // Drop any replies queued but not yet transmitted so they don't leak
        // into the next session.
        while REPLY_CHANNEL.try_receive().is_ok() {}
    }
}
