//! Minimal Deluge SDK example.
//!
//! Blinks the heartbeat LED (P6_7) — the same LED the demo firmware toggles —
//! with nothing but an `async` loop. All platform bring-up (heaps, clocks,
//! interrupts, executor, panic handler) is generated by `#[deluge::app]`.

#![no_std]
#![no_main]
// Required by `#[embassy_executor::task]`, which the `#[deluge::app]` expansion
// uses to wrap `main`.
#![feature(impl_trait_in_assoc_type)]

use deluge::prelude::*;
use deluge::rza1l_hal::gpio;
use embassy_time::Timer;

/// Heartbeat LED — port 6, pin 7.
const LED_PORT: u8 = 6;
const LED_PIN: u8 = 7;

#[deluge::app]
async fn main(_dlg: Deluge) {
    // SAFETY: single owner of P6_7; configured once before the loop.
    unsafe { gpio::set_as_output(LED_PORT, LED_PIN) };

    let mut on = false;
    loop {
        on = !on;
        // SAFETY: GPIO write to a pin we own.
        unsafe { gpio::write(LED_PORT, LED_PIN, on) };
        Timer::after_millis(200).await;
    }
}
