//! Minimal Deluge SDK example.
//!
//! Blinks the SYNC LED with nothing but an `async` loop. All platform
//! bring-up (heaps, clocks, interrupts, executor, panic handler) is generated by
//! `#[deluge::app]`, and the LED is an owned capability taken from the handle —
//! no `unsafe`, no raw register pokes.

#![cfg_attr(target_os = "none", no_std)]
#![cfg_attr(target_os = "none", no_main)]
// Required by `#[embassy_executor::task]`, which the `#[deluge::app]` expansion
// uses to wrap `main`.
#![feature(impl_trait_in_assoc_type)]

use deluge::prelude::*;
use embassy_time::Timer;

#[deluge::app]
async fn main(dlg: Deluge) {
    let mut led = dlg.sync_led();
    loop {
        led.toggle();
        Timer::after_millis(200).await;
    }
}
