//! Icon definitions from Deluge firmware
//!
//! Icons are embedded at compile time from BMP files extracted from the Deluge firmware.
//! The BMP files are generated by util/extract_deluge_icons.py from oled_icons.cpp

/// Icon format type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IconFormat {
    /// Raw bitmap data (legacy format)
    RawBitmap,
    /// Embedded BMP file
    Bmp,
}

/// Icon bitmap data
#[derive(Debug, Clone, Copy)]
pub struct IconData {
    /// Raw data (BMP file bytes or column-major bitmap)
    pub data: &'static [u8],
    /// Width in pixels
    pub width: u8,
    /// Height in pixels  
    pub height: u8,
    /// Format of the icon data
    pub format: IconFormat,
}

impl IconData {
    /// Create an icon from embedded BMP data
    pub const fn from_bmp(bmp_data: &'static [u8]) -> Self {
        // Parse BMP header at compile time
        // Width is at offset 18 (4 bytes, little-endian)
        let width =
            u32::from_le_bytes([bmp_data[18], bmp_data[19], bmp_data[20], bmp_data[21]]) as u8;

        // Height is at offset 22 (4 bytes, little-endian, signed)
        // We take absolute value since BMP can be top-down (negative) or bottom-up (positive)
        let height_bytes = [bmp_data[22], bmp_data[23], bmp_data[24], bmp_data[25]];
        let height_i32 = i32::from_le_bytes(height_bytes);
        let height = if height_i32 < 0 {
            (-height_i32) as u8
        } else {
            height_i32 as u8
        };

        Self {
            data: bmp_data,
            width,
            height,
            format: IconFormat::Bmp,
        }
    }
}

/// Helper to get pixel from BMP data at runtime
pub fn get_bmp_pixel(icon: &IconData, x: u8, y: u8) -> bool {
    if icon.format != IconFormat::Bmp {
        return false;
    }

    let bmp_data = icon.data;

    // Calculate row size (padded to 4-byte boundary)
    let row_size_bytes = (icon.width as usize).div_ceil(8);
    let row_size_padded = row_size_bytes.div_ceil(4) * 4;

    // Pixel data starts at offset 62 (14 + 40 + 8 for 1-bit BMP)
    let pixel_data_offset = 62;

    // BMP stores rows from bottom to top
    let row_from_bottom = (icon.height - 1 - y) as usize;
    let row_offset = pixel_data_offset + row_from_bottom * row_size_padded;

    let byte_idx = x as usize / 8;
    let bit_idx = 7 - (x as usize % 8); // MSB first in BMP

    if row_offset + byte_idx < bmp_data.len() {
        (bmp_data[row_offset + byte_idx] & (1 << bit_idx)) != 0
    } else {
        false
    }
}

// Include generated icon constants from build.rs
include!(concat!(env!("OUT_DIR"), "/generated_icons.rs"));
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_icon_widths() {
        assert_eq!(CHECKED_BOX.width, 7);
        assert_eq!(UNCHECKED_BOX.width, 7);
        assert_eq!(SUBMENU_ARROW.width, 7);
        assert_eq!(DOWN_ARROW.width, 5);
        assert_eq!(RIGHT_ARROW.width, 3);
        assert_eq!(FOLDER.width, 8);
        assert_eq!(WAVE.width, 8);
        assert_eq!(SYNTH.width, 8);
        assert_eq!(KIT.width, 8);
        assert_eq!(MIDI.width, 9);
        assert_eq!(SONG.width, 9);

        // 16px tall icons
        assert_eq!(SINE.width, 25);
        assert_eq!(SQUARE.width, 23);
        assert_eq!(TRIANGLE.width, 25);
        assert_eq!(SAW.width, 25);
    }

    #[test]
    fn test_icon_heights() {
        // 7px tall icons
        assert_eq!(CHECKED_BOX.height, 7);
        assert_eq!(FOLDER.height, 7);

        // 16px tall icons
        assert_eq!(SINE.height, 16);
        assert_eq!(SQUARE.height, 16);
        assert_eq!(TRIANGLE.height, 16);
    }

    #[test]
    fn test_icon_data_integrity() {
        // Verify icons have BMP file data
        // 7-pixel tall icons are 90 bytes (14 byte header + 40 byte info + 8 byte palette + 28 pixel data)
        assert_eq!(CHECKED_BOX.data.len(), 90);
        assert_eq!(FOLDER.data.len(), 90);
        assert_eq!(SONG.data.len(), 90);

        // 16-pixel tall icons are 126 bytes (14 byte header + 40 byte info + 8 byte palette + 64 pixel data)
        assert_eq!(SINE.data.len(), 126);
        assert_eq!(SQUARE.data.len(), 126);
    }
}
