//! Icon definitions from Deluge firmware
//!
//! Icons are embedded at compile time from BMP files extracted from the Deluge firmware.
//! The BMP files are generated by util/extract_deluge_icons.py from oled_icons.cpp

/// Icon format type
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IconFormat {
    /// Raw row-major bitmap, 1 bit per pixel, MSB = leftmost pixel.
    RawBitmap,
    /// Embedded BMP file
    Bmp,
}

/// Icon bitmap data
#[derive(Debug, Clone, Copy)]
pub struct IconData {
    /// Icon bytes: a whole BMP file, or a raw bitmap (see [`IconFormat`]).
    pub data: &'static [u8],
    /// Width in pixels
    pub width: u8,
    /// Height in pixels  
    pub height: u8,
    /// Format of the icon data
    pub format: IconFormat,
}

impl IconData {
    /// Create an icon from embedded BMP data
    pub const fn from_bmp(bmp_data: &'static [u8]) -> Self {
        // BITMAPINFOHEADER width: offset 18, 4 bytes little-endian.
        let width =
            u32::from_le_bytes([bmp_data[18], bmp_data[19], bmp_data[20], bmp_data[21]]) as u8;

        // Height: offset 22, signed; negative means a top-down BMP, so take the
        // magnitude.
        let height_bytes = [bmp_data[22], bmp_data[23], bmp_data[24], bmp_data[25]];
        let height_i32 = i32::from_le_bytes(height_bytes);
        let height = if height_i32 < 0 {
            (-height_i32) as u8
        } else {
            height_i32 as u8
        };

        Self {
            data: bmp_data,
            width,
            height,
            format: IconFormat::Bmp,
        }
    }
}

/// Whether pixel `(x, y)` of a 1-bit BMP icon is lit. Returns `false` for
/// non-BMP icons or if the pixel's byte lies past the end of the data;
/// `y` must be less than the icon height.
///
/// Assumes bottom-up row order and a 62-byte header (file header + 40-byte
/// info header + 2-entry palette).
pub fn get_bmp_pixel(icon: &IconData, x: u8, y: u8) -> bool {
    if icon.format != IconFormat::Bmp {
        return false;
    }

    let bmp_data = icon.data;

    // BMP rows are padded to a 4-byte boundary.
    let row_size_bytes = (icon.width as usize).div_ceil(8);
    let row_size_padded = row_size_bytes.div_ceil(4) * 4;

    let pixel_data_offset = 62;

    let row_from_bottom = (icon.height - 1 - y) as usize;
    let row_offset = pixel_data_offset + row_from_bottom * row_size_padded;

    let byte_idx = x as usize / 8;
    let bit_idx = 7 - (x as usize % 8); // MSB first in BMP

    if row_offset + byte_idx < bmp_data.len() {
        (bmp_data[row_offset + byte_idx] & (1 << bit_idx)) != 0
    } else {
        false
    }
}

// One `IconData` constant per BMP in `assets/icons/`, generated by build.rs.
include!(concat!(env!("OUT_DIR"), "/generated_icons.rs"));
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_icon_widths() {
        assert_eq!(CHECKED_BOX.width, 7);
        assert_eq!(UNCHECKED_BOX.width, 7);
        assert_eq!(SUBMENU_ARROW.width, 7);
        assert_eq!(DOWN_ARROW.width, 5);
        assert_eq!(RIGHT_ARROW.width, 3);
        assert_eq!(FOLDER.width, 8);
        assert_eq!(WAVE.width, 8);
        assert_eq!(SYNTH.width, 8);
        assert_eq!(KIT.width, 8);
        assert_eq!(MIDI.width, 9);
        assert_eq!(SONG.width, 9);

        // 16px tall icons
        assert_eq!(SINE.width, 25);
        assert_eq!(SQUARE.width, 23);
        assert_eq!(TRIANGLE.width, 25);
        assert_eq!(SAW.width, 25);
    }

    #[test]
    fn test_icon_heights() {
        // 7px tall icons
        assert_eq!(CHECKED_BOX.height, 7);
        assert_eq!(FOLDER.height, 7);

        // 16px tall icons
        assert_eq!(SINE.height, 16);
        assert_eq!(SQUARE.height, 16);
        assert_eq!(TRIANGLE.height, 16);
    }

    #[test]
    fn test_icon_data_integrity() {
        // Verify icons have BMP file data
        // 7-pixel tall icons are 90 bytes (14 byte header + 40 byte info + 8 byte palette + 28 pixel data)
        assert_eq!(CHECKED_BOX.data.len(), 90);
        assert_eq!(FOLDER.data.len(), 90);
        assert_eq!(SONG.data.len(), 90);

        // 16-pixel tall icons are 126 bytes (14 byte header + 40 byte info + 8 byte palette + 64 pixel data)
        assert_eq!(SINE.data.len(), 126);
        assert_eq!(SQUARE.data.len(), 126);
    }
}
