name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  firmware:
    name: Firmware
    uses: ./.github/workflows/firmware.yml
    with:
      build-type: release
      retention-days: 7

  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
