name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  examples:
    name: Examples
    uses: ./.github/workflows/examples.yml

  images:
    name: Images
    uses: ./.github/workflows/images.yml
    with:
      retention-days: 7

  tests:
    name: Tests
    uses: ./.github/workflows/test.yml
